version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    #volumes:
      #- data01:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - "node.role==worker"

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    #volumes:
    #  - data02:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - "node.role==worker"

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    #volumes:
    #  - data03:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - "node.role==worker"

  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    container_name: elasticsearch_exporter
    command:
      - '--es.all'
    restart: always
    ports:
      - 9114:9114
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  prometheus:
    image: prom/prometheus:0.18.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    restart: always
    ports:
      - 9090:9090
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    links:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==manager"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: overlay
