version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==worker"

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - ./slave.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      placement:
        constraints:
          - "node.role==worker"

  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    container_name: elasticsearch_exporter
    command:
      - '--es.all'
    restart: always
    ports:
      - 9114:9114
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  prometheus:
    image: prom/prometheus:0.18.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    restart: always
    ports:
      - 9090:9090
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    links:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.role==manager"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: overlay
