# Define two scrapers
#   1. docker - which collects the matrixes of docker
#   2. eexporter - which collects the matrixes of elasticsearch
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'lambda-monitor'
scrape_configs:
  - job_name: 'docker'
    target_groups:
      - targets: ['localhost:9841']
  - job_name: 'eexporter'
    target_groups:
      - targets: ['localhost:9114']
